import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { test } from 'node:test';

const apiSource = readFileSync(new URL('../../../src/api/matches.ts', import.meta.url), 'utf8');
const detailSource = readFileSync(new URL('../../../src/pages/matches/MatchDetail.tsx', import.meta.url), 'utf8');
const dtoSource = readFileSync(new URL('../../../../PicklinkBackend/PicklinkBackend/DTOs/MatchRequest.cs', import.meta.url), 'utf8');
const matchServiceSource = readFileSync(new URL('../../../../PicklinkBackend/PicklinkBackend/Services/Matches/Implementations/MatchService.cs', import.meta.url), 'utf8');
const replacementResponseSource = readFileSync(new URL('../../../../PicklinkBackend/PicklinkBackend/Services/Matches/Implementations/MatchService.ReplacementResponses.cs', import.meta.url), 'utf8');

test('match room frontend reveals only the personal code returned for a check-in group', () => {
  assert.ok(apiSource.includes('export type MatchBookingCheckInGroup'));
  assert.ok(apiSource.includes('checkInCode?: string | null;'));
  assert.ok(apiSource.includes('isCheckInWindowOpen: boolean;'));
  assert.ok(apiSource.includes('bookingCheckIns: MatchBookingCheckIn[];'));
  assert.ok(apiSource.includes('getMatchBookingRounds'));
  assert.ok(apiSource.includes('/booking-rounds${queryString(pagination)}'));
  assert.ok(apiSource.includes('totalBookingAmount: number;'));
  assert.ok(apiSource.includes('venueAddress?: string | null;'));
  assert.ok(dtoSource.includes('class MatchBookingCheckInResponse'));
  assert.ok(dtoSource.includes('public string? VenueAddress { get; set; }'));
  assert.ok(dtoSource.includes('public decimal TotalBookingAmount { get; set; }'));
  assert.ok(dtoSource.includes('class MatchBookingCheckInGroupResponse'));
  assert.ok(dtoSource.includes('public bool IsCheckInWindowOpen { get; set; }'));
  assert.ok(detailSource.includes("group.checkInCode && booking.bookingStatus === 'Confirmed' && group.isCheckInWindowOpen"));
  assert.ok(detailSource.includes('{group.checkInCode}</div>'));
  assert.ok(detailSource.includes('group.isCheckInWindowOpen ?'));
  assert.ok(!detailSource.includes('match.checkInCode'));
  assert.ok(detailSource.includes('Mã check-in cá nhân của bạn'));
  assert.ok(detailSource.includes('Các lượt booking'));
  assert.ok(detailSource.includes('Xem các lượt booking'));
  assert.ok(!detailSource.includes('Xem danh sách (${match.bookingCheckIns.length})'));
  assert.ok(detailSource.includes('Mã mở trước giờ chơi 30 phút.'));
  assert.ok(detailSource.includes('matchBookingRoundTotalLabel(booking, match)'));
  assert.ok(!detailSource.includes('currency.format(booking.amountPerPlayer)'));
  assert.ok(detailSource.includes('booking.venueAddress'));
  assert.ok(detailSource.includes('mergeAdjacentMatchBookingCheckInGroups'));
  assert.ok(detailSource.includes('groups={mergedGroup.groups}'));
  assert.ok(detailSource.includes('mergedGroup.groups.slice(0, 1)'));
  assert.ok(detailSource.includes('displayedBookingRounds'));
  assert.ok(detailSource.includes('loadMoreBookingRounds'));
  assert.ok(detailSource.includes('bookingRoundsTotalCount'));
  assert.ok(matchServiceSource.includes('BuildVisibleBookingRoundsAsync('));
  assert.ok(!matchServiceSource.includes('CheckInCode = g.CheckInCode'));
  assert.ok(replacementResponseSource.includes('payment.PayerId == currentPlayerId && payment.Status == "Paid"'));
  assert.ok(replacementResponseSource.includes('booking.Status == "Confirmed"'));
  assert.ok(replacementResponseSource.includes('localNow >= group.StartTime.AddMinutes(-30)'));
});
