import {
  AlertTriangle,
  BadgeCheck,
  Banknote,
  CalendarCheck,
  CheckCircle2,
  ClipboardCheck,
  CreditCard,
  FileText,
  Flag,
  LandPlot,
  Lock,
  RefreshCcw,
  Settings,
  ShieldCheck,
  Star,
  UserCheck,
  Users,
  UsersRound,
  XCircle,
} from 'lucide-react';
import type { AdminConfig, AdminDataSectionId, SettingGroup } from './types';

export const sectionConfigs: Record<AdminDataSectionId, AdminConfig> = {
  overview: {
    id: 'overview',
    eyebrow: 'Báº£ng Ä‘iá»u khiá»ƒn',
    title: 'Tá»•ng quan quáº£n trá»‹',
    description: 'Theo dÃµi váº­n hÃ nh Picklink theo thá»i gian thá»±c, Æ°u tiÃªn cÃ¡c viá»‡c cáº§n duyá»‡t vÃ  cÃ¡c cáº£nh bÃ¡o rá»§i ro.',
    primaryAction: 'Xuáº¥t bÃ¡o cÃ¡o',
    searchPlaceholder: 'TÃ¬m luá»“ng xá»­ lÃ½, ngÆ°á»i phá»¥ trÃ¡ch...',
    filters: ['Táº¥t cáº£', 'Æ¯u tiÃªn cao', 'Äang xá»­ lÃ½', 'á»”n Ä‘á»‹nh'],
    stats: [
      { label: 'NgÆ°á»i dÃ¹ng', value: '12.480', helper: '+248 trong thÃ¡ng', icon: Users },
      { label: 'SÃ¢n Ä‘ang hoáº¡t Ä‘á»™ng', value: '428', helper: '34 sÃ¢n chá» duyá»‡t', icon: LandPlot },
      { label: 'Booking hÃ´m nay', value: '1.286', helper: '96,4% thanh toÃ¡n thÃ nh cÃ´ng', icon: CalendarCheck },
      { label: 'BÃ¡o cÃ¡o má»Ÿ', value: '37', helper: '8 vá»¥ Æ°u tiÃªn cao', icon: AlertTriangle },
    ],
    columns: ['Luá»“ng xá»­ lÃ½', 'Æ¯u tiÃªn', 'Phá»¥ trÃ¡ch', 'SLA'],
    rows: [
      {
        id: 'ops-01',
        cells: ['Duyá»‡t sÃ¢n má»›i khu vá»±c HÃ  Ná»™i', 'Æ¯u tiÃªn cao', 'NhÃ³m váº­n hÃ nh', '2 giá»'],
        status: 'Äang xá»­ lÃ½',
        statusTone: 'warning',
        filters: ['Æ¯u tiÃªn cao', 'Äang xá»­ lÃ½'],
        actions: ['Má»Ÿ hÃ ng chá»', 'PhÃ¢n cÃ´ng'],
      },
      {
        id: 'ops-02',
        cells: ['Äá»‘i soÃ¡t hoÃ n tiá»n cuá»‘i ngÃ y', 'Trung bÃ¬nh', 'TÃ i chÃ­nh', '18:00'],
        status: 'á»”n Ä‘á»‹nh',
        statusTone: 'success',
        filters: ['á»”n Ä‘á»‹nh'],
        actions: ['Xem chi tiáº¿t'],
      },
      {
        id: 'ops-03',
        cells: ['BÃ¡o cÃ¡o bÃ i viáº¿t cá»™ng Ä‘á»“ng', 'Æ¯u tiÃªn cao', 'Kiá»ƒm duyá»‡t', '30 phÃºt'],
        status: 'Äang xá»­ lÃ½',
        statusTone: 'warning',
        filters: ['Æ¯u tiÃªn cao', 'Äang xá»­ lÃ½'],
        actions: ['Kiá»ƒm duyá»‡t', 'Gáº¯n cá»'],
      },
      {
        id: 'ops-04',
        cells: ['TÃ¬nh tráº¡ng thanh toÃ¡n online', 'Tháº¥p', 'Ká»¹ thuáº­t', 'Theo dÃµi'],
        status: 'á»”n Ä‘á»‹nh',
        statusTone: 'success',
        filters: ['á»”n Ä‘á»‹nh'],
        actions: ['Xem log'],
      },
    ],
    queueTitle: 'Viá»‡c cáº§n chÃº Ã½',
    queues: [
      { label: 'SÃ¢n chá» duyá»‡t', value: '34', tone: 'warning' },
      { label: 'BÃ¡o cÃ¡o quÃ¡ háº¡n', value: '8', tone: 'danger' },
      { label: 'HoÃ n tiá»n cáº§n xÃ¡c nháº­n', value: '12', tone: 'info' },
    ],
  },
  users: {
    id: 'users',
    eyebrow: 'TÃ i khoáº£n',
    title: 'Quáº£n lÃ½ ngÆ°á»i dÃ¹ng',
    description: 'Quáº£n lÃ½ tÃ i khoáº£n ngÆ°á»i chÆ¡i, chá»§ sÃ¢n, quáº£n trá»‹ viÃªn, tráº¡ng thÃ¡i khÃ³a/má»Ÿ vÃ  xÃ¡c minh thÃ´ng tin.',
    primaryAction: 'ThÃªm quáº£n trá»‹ viÃªn',
    searchPlaceholder: 'TÃ¬m tÃªn, email, sá»‘ Ä‘iá»‡n thoáº¡i...',
    filters: ['Táº¥t cáº£', 'NgÆ°á»i chÆ¡i', 'Chá»§ sÃ¢n', 'Admin', 'ÄÃ£ khÃ³a'],
    stats: [
      { label: 'Tá»•ng tÃ i khoáº£n', value: '12.480', helper: '9.840 ngÆ°á»i chÆ¡i', icon: Users },
      { label: 'Chá» xÃ¡c minh', value: '126', helper: 'Cáº§n kiá»ƒm tra CCCD/SÄT', icon: BadgeCheck },
      { label: 'ÄÃ£ khÃ³a', value: '42', helper: '12 tÃ i khoáº£n trong 7 ngÃ y', icon: Lock },
      { label: 'Hoáº¡t Ä‘á»™ng hÃ´m nay', value: '3.816', helper: '+18% so vá»›i hÃ´m qua', icon: UserCheck },
    ],
    columns: ['NgÆ°á»i dÃ¹ng', 'Email', 'Vai trÃ²', 'Sá»‘ Ä‘iá»‡n thoáº¡i', 'NgÃ y táº¡o'],
    rows: [
      {
        id: 'user-01',
        cells: ['Nguyá»…n VÄƒn An', 'an.nguyen@gmail.com', 'NgÆ°á»i chÆ¡i', '0901 234 567', '12/05/2026'],
        status: 'Hoáº¡t Ä‘á»™ng',
        statusTone: 'success',
        filters: ['NgÆ°á»i chÆ¡i'],
        actions: ['Xem', 'KhÃ³a'],
      },
      {
        id: 'user-02',
        cells: ['Tráº§n Thá»‹ BÃ¬nh', 'binh.tran@yahoo.com', 'Chá»§ sÃ¢n', '0912 233 445', '15/05/2026'],
        status: 'Chá» xÃ¡c minh',
        statusTone: 'warning',
        filters: ['Chá»§ sÃ¢n'],
        actions: ['Duyá»‡t', 'YÃªu cáº§u bá»• sung'],
      },
      {
        id: 'user-03',
        cells: ['LÃª HoÃ ng CÆ°á»ng', 'cuong.le@outlook.com', 'NgÆ°á»i chÆ¡i', '0988 776 655', '20/05/2026'],
        status: 'ÄÃ£ khÃ³a',
        statusTone: 'danger',
        filters: ['NgÆ°á»i chÆ¡i', 'ÄÃ£ khÃ³a'],
        actions: ['Má»Ÿ khÃ³a', 'Xem lá»‹ch sá»­'],
      },
      {
        id: 'user-04',
        cells: ['HoÃ ng Báº£o Anh', 'anh.hoang@picklink.vn', 'Admin', '0944 556 677', '01/01/2026'],
        status: 'Hoáº¡t Ä‘á»™ng',
        statusTone: 'success',
        filters: ['Admin'],
        actions: ['PhÃ¢n quyá»n', 'Nháº­t kÃ½'],
      },
    ],
    queueTitle: 'HÃ ng chá» tÃ i khoáº£n',
    queues: [
      { label: 'Há»“ sÆ¡ chá»§ sÃ¢n cáº§n duyá»‡t', value: '18', tone: 'warning' },
      { label: 'TÃ i khoáº£n bá»‹ bÃ¡o cÃ¡o', value: '11', tone: 'danger' },
      { label: 'YÃªu cáº§u Ä‘á»•i sá»‘ Ä‘iá»‡n thoáº¡i', value: '24', tone: 'info' },
    ],
  },
  courts: {
    id: 'courts',
    eyebrow: 'SÃ¢n pickleball',
    title: 'Duyá»‡t sÃ¢n, khÃ³a/má»Ÿ sÃ¢n',
    description: 'Kiá»ƒm tra há»“ sÆ¡ sÃ¢n, áº£nh, Ä‘á»‹a chá»‰, tiá»‡n Ã­ch vÃ  tráº¡ng thÃ¡i hoáº¡t Ä‘á»™ng cá»§a tá»«ng cá»¥m sÃ¢n trÃªn há»‡ thá»‘ng.',
    primaryAction: 'Duyá»‡t hÃ ng loáº¡t',
    searchPlaceholder: 'TÃ¬m tÃªn sÃ¢n, chá»§ sÃ¢n, Ä‘á»‹a chá»‰...',
    filters: ['Táº¥t cáº£', 'Chá» duyá»‡t', 'Hoáº¡t Ä‘á»™ng', 'ÄÃ£ khÃ³a', 'Cáº§n kiá»ƒm tra'],
    stats: [
      { label: 'Cá»¥m sÃ¢n', value: '428', helper: '1.936 sÃ¢n con', icon: LandPlot },
      { label: 'Chá» duyá»‡t', value: '34', helper: '12 há»“ sÆ¡ thiáº¿u áº£nh', icon: ClipboardCheck },
      { label: 'ÄÃ£ khÃ³a', value: '16', helper: 'Do vi pháº¡m chÃ­nh sÃ¡ch', icon: Lock },
      { label: 'Khiáº¿u náº¡i má»Ÿ', value: '9', helper: 'Cáº§n pháº£n há»“i chá»§ sÃ¢n', icon: AlertTriangle },
    ],
    columns: ['Cá»¥m sÃ¢n', 'Chá»§ sÃ¢n', 'Äá»‹a chá»‰', 'Sá»‘ sÃ¢n', 'Cáº­p nháº­t'],
    rows: [
      {
        id: 'court-01',
        cells: ['Pickleball Diamond Q7', 'Nguyá»…n HoÃ ng Nam', 'Quáº­n 7, TP. Há»“ ChÃ­ Minh', '8 sÃ¢n', '18/06/2026'],
        status: 'Hoáº¡t Ä‘á»™ng',
        statusTone: 'success',
        filters: ['Hoáº¡t Ä‘á»™ng'],
        actions: ['Xem', 'KhÃ³a'],
      },
      {
        id: 'court-02',
        cells: ['SÃ¢n Pickleball Tháº£o Äiá»n', 'Tráº§n VÄƒn TÃº', 'TP. Thá»§ Äá»©c, TP. Há»“ ChÃ­ Minh', '4 sÃ¢n', '17/06/2026'],
        status: 'Chá» duyá»‡t',
        statusTone: 'warning',
        filters: ['Chá» duyá»‡t'],
        actions: ['Duyá»‡t', 'Tá»« chá»‘i'],
      },
      {
        id: 'court-03',
        cells: ['Há»“ TÃ¢y Pickleball Club', 'Pháº¡m Thanh TÃ¹ng', 'TÃ¢y Há»“, HÃ  Ná»™i', '12 sÃ¢n', '16/06/2026'],
        status: 'Cáº§n kiá»ƒm tra',
        statusTone: 'info',
        filters: ['Cáº§n kiá»ƒm tra'],
        actions: ['Kiá»ƒm tra', 'Nháº¯n chá»§ sÃ¢n'],
      },
      {
        id: 'court-04',
        cells: ['SÃ¢n Cáº§u Giáº¥y Gold', 'LÃª Minh QuÃ¢n', 'Cáº§u Giáº¥y, HÃ  Ná»™i', '6 sÃ¢n', '14/06/2026'],
        status: 'ÄÃ£ khÃ³a',
        statusTone: 'danger',
        filters: ['ÄÃ£ khÃ³a'],
        actions: ['Má»Ÿ khÃ³a', 'Xem lÃ½ do'],
      },
    ],
    queueTitle: 'Kiá»ƒm duyá»‡t sÃ¢n',
    queues: [
      { label: 'Chá» duyá»‡t há»“ sÆ¡', value: '34', tone: 'warning' },
      { label: 'Cáº§n xÃ¡c minh Ä‘á»‹a chá»‰', value: '7', tone: 'info' },
      { label: 'Vi pháº¡m áº£nh/giÃ¡', value: '5', tone: 'danger' },
    ],
  },
  clubs: {
    id: 'clubs',
    eyebrow: 'CÃ¢u láº¡c bá»™',
    title: 'Duyá»‡t CLB, xá»­ lÃ½ CLB vi pháº¡m',
    description: 'Theo dÃµi CLB má»›i, cáº£nh bÃ¡o ná»™i dung vi pháº¡m, thÃ nh viÃªn bá»‹ bÃ¡o cÃ¡o vÃ  tráº¡ng thÃ¡i hoáº¡t Ä‘á»™ng cá»§a CLB.',
    primaryAction: 'Táº¡o thÃ´ng bÃ¡o',
    searchPlaceholder: 'TÃ¬m tÃªn CLB, chá»§ nhiá»‡m, khu vá»±c...',
    filters: ['Táº¥t cáº£', 'Chá» duyá»‡t', 'Hoáº¡t Ä‘á»™ng', 'Bá»‹ cáº£nh bÃ¡o', 'ÄÃ£ khÃ³a'],
    stats: [
      { label: 'Tá»•ng CLB', value: '246', helper: '18 CLB má»›i trong thÃ¡ng', icon: UsersRound },
      { label: 'Chá» duyá»‡t', value: '19', helper: 'Æ¯u tiÃªn CLB cÃ³ Ä‘á»§ há»“ sÆ¡', icon: ClipboardCheck },
      { label: 'Bá»‹ cáº£nh bÃ¡o', value: '8', helper: 'Ná»™i dung hoáº·c thÃ nh viÃªn', icon: AlertTriangle },
      { label: 'Sá»± kiá»‡n thÃ¡ng nÃ y', value: '73', helper: '12 sá»± kiá»‡n Ä‘ang má»Ÿ', icon: CalendarCheck },
    ],
    columns: ['CLB', 'Chá»§ nhiá»‡m', 'Khu vá»±c', 'ThÃ nh viÃªn', 'BÃ¡o cÃ¡o'],
    rows: [
      {
        id: 'club-01',
        cells: ['Saigon Pickle Crew', 'Minh Khang', 'TP. Há»“ ChÃ­ Minh', '218', '0'],
        status: 'Hoáº¡t Ä‘á»™ng',
        statusTone: 'success',
        filters: ['Hoáº¡t Ä‘á»™ng'],
        actions: ['Xem', 'Gá»­i nháº¯c nhá»Ÿ'],
      },
      {
        id: 'club-02',
        cells: ['Há»“ TÃ¢y Smashers', 'Ngá»c Anh', 'HÃ  Ná»™i', '84', '2'],
        status: 'Bá»‹ cáº£nh bÃ¡o',
        statusTone: 'danger',
        filters: ['Bá»‹ cáº£nh bÃ¡o'],
        actions: ['Xá»­ lÃ½', 'KhÃ³a CLB'],
      },
      {
        id: 'club-03',
        cells: ['ÄÃ  Náºµng Rally Hub', 'Quá»‘c Huy', 'ÄÃ  Náºµng', '42', '0'],
        status: 'Chá» duyá»‡t',
        statusTone: 'warning',
        filters: ['Chá» duyá»‡t'],
        actions: ['Duyá»‡t', 'Tá»« chá»‘i'],
      },
      {
        id: 'club-04',
        cells: ['Cáº§u Giáº¥y Weekend Club', 'HoÃ i Nam', 'HÃ  Ná»™i', '136', '1'],
        status: 'Hoáº¡t Ä‘á»™ng',
        statusTone: 'success',
        filters: ['Hoáº¡t Ä‘á»™ng'],
        actions: ['Xem bÃ i viáº¿t', 'Nháº­t kÃ½'],
      },
    ],
    queueTitle: 'Cáº§n xá»­ lÃ½ CLB',
    queues: [
      { label: 'CLB chá» duyá»‡t', value: '19', tone: 'warning' },
      { label: 'CLB cÃ³ bÃ¡o cÃ¡o má»Ÿ', value: '8', tone: 'danger' },
      { label: 'Sá»± kiá»‡n cáº§n xÃ¡c minh', value: '6', tone: 'info' },
    ],
  },
  bookings: {
    id: 'bookings',
    eyebrow: 'Booking toÃ n há»‡ thá»‘ng',
    title: 'Theo dÃµi booking toÃ n há»‡ thá»‘ng',
    description: 'GiÃ¡m sÃ¡t Ä‘Æ¡n Ä‘áº·t sÃ¢n, thanh toÃ¡n, check-in, há»§y lá»‹ch vÃ  cÃ¡c booking cÃ³ tranh cháº¥p giá»¯a ngÆ°á»i chÆ¡i vá»›i chá»§ sÃ¢n.',
    primaryAction: 'Táº£i danh sÃ¡ch',
    searchPlaceholder: 'TÃ¬m mÃ£ booking, ngÆ°á»i Ä‘áº·t, sÃ¢n...',
    filters: ['Táº¥t cáº£', 'ÄÃ£ thanh toÃ¡n', 'Chá» thanh toÃ¡n', 'ÄÃ£ há»§y', 'Tranh cháº¥p'],
    stats: [
      { label: 'Booking hÃ´m nay', value: '1.286', helper: '876 Ä‘Ã£ check-in', icon: CalendarCheck },
      { label: 'Doanh thu giá»¯ chá»—', value: '486,2tr', helper: 'TÄƒng 14% so vá»›i hÃ´m qua', icon: Banknote },
      { label: 'Chá» thanh toÃ¡n', value: '74', helper: 'Tá»± há»§y sau 5 phÃºt', icon: CreditCard },
      { label: 'Tranh cháº¥p', value: '6', helper: 'Cáº§n admin can thiá»‡p', icon: AlertTriangle },
    ],
    columns: ['MÃ£ Ä‘Æ¡n', 'NgÆ°á»i Ä‘áº·t', 'SÃ¢n', 'Thá»i gian', 'Thanh toÃ¡n'],
    rows: [
      {
        id: 'booking-01',
        cells: ['BK-260618-0142', 'Nguyá»…n VÄƒn An', 'Diamond Q7 - SÃ¢n 03', '18/06/2026 19:00', '520.000Ä‘'],
        status: 'ÄÃ£ thanh toÃ¡n',
        statusTone: 'success',
        filters: ['ÄÃ£ thanh toÃ¡n'],
        actions: ['Xem', 'Há»— trá»£'],
      },
      {
        id: 'booking-02',
        cells: ['BK-260618-0157', 'Tráº§n Má»¹ Linh', 'Há»“ TÃ¢y Club - SÃ¢n 08', '18/06/2026 20:30', '680.000Ä‘'],
        status: 'Chá» thanh toÃ¡n',
        statusTone: 'warning',
        filters: ['Chá» thanh toÃ¡n'],
        actions: ['Nháº¯c thanh toÃ¡n', 'Há»§y giá»¯ chá»—'],
      },
      {
        id: 'booking-03',
        cells: ['BK-260617-0288', 'Pháº¡m Quá»‘c Huy', 'Tháº£o Äiá»n - SÃ¢n 02', '17/06/2026 17:30', '420.000Ä‘'],
        status: 'Tranh cháº¥p',
        statusTone: 'danger',
        filters: ['Tranh cháº¥p'],
        actions: ['Má»Ÿ vá»¥ viá»‡c', 'HoÃ n tiá»n'],
      },
      {
        id: 'booking-04',
        cells: ['BK-260616-0094', 'Äá»— Háº£i Nam', 'Cáº§u Giáº¥y Gold - SÃ¢n 01', '16/06/2026 06:00', '300.000Ä‘'],
        status: 'ÄÃ£ há»§y',
        statusTone: 'neutral',
        filters: ['ÄÃ£ há»§y'],
        actions: ['Xem lÃ½ do'],
      },
    ],
    queueTitle: 'HÃ ng chá» booking',
    queues: [
      { label: 'Chá» thanh toÃ¡n', value: '74', tone: 'warning' },
      { label: 'YÃªu cáº§u hoÃ n tiá»n', value: '18', tone: 'info' },
      { label: 'Tranh cháº¥p quÃ¡ háº¡n', value: '3', tone: 'danger' },
    ],
  },
  reports: {
    id: 'reports',
    eyebrow: 'An toÃ n cá»™ng Ä‘á»“ng',
    title: 'Xá»­ lÃ½ bÃ¡o cÃ¡o ngÆ°á»i chÆ¡i, bÃ i viáº¿t, sÃ¢n, CLB',
    description: 'Táº­p trung cÃ¡c bÃ¡o cÃ¡o vi pháº¡m Ä‘á»ƒ admin phÃ¢n loáº¡i, Æ°u tiÃªn xá»­ lÃ½, pháº£n há»“i ngÆ°á»i gá»­i vÃ  ghi láº¡i káº¿t quáº£.',
    primaryAction: 'PhÃ¢n cÃ´ng bÃ¡o cÃ¡o',
    searchPlaceholder: 'TÃ¬m mÃ£ bÃ¡o cÃ¡o, Ä‘á»‘i tÆ°á»£ng, ngÆ°á»i gá»­i...',
    filters: ['Táº¥t cáº£', 'NgÆ°á»i chÆ¡i', 'BÃ i viáº¿t', 'SÃ¢n', 'CLB', 'Æ¯u tiÃªn cao'],
    stats: [
      { label: 'BÃ¡o cÃ¡o má»Ÿ', value: '37', helper: '8 Æ°u tiÃªn cao', icon: Flag },
      { label: 'ÄÃ£ xá»­ lÃ½ hÃ´m nay', value: '21', helper: 'SLA trung bÃ¬nh 42 phÃºt', icon: CheckCircle2 },
      { label: 'QuÃ¡ háº¡n', value: '5', helper: 'Cáº§n trÆ°á»Ÿng nhÃ³m duyá»‡t', icon: AlertTriangle },
      { label: 'TÃ¡i pháº¡m', value: '12', helper: 'TÃ i khoáº£n/CLB cÃ³ lá»‹ch sá»­', icon: RefreshCcw },
    ],
    columns: ['MÃ£ bÃ¡o cÃ¡o', 'Loáº¡i', 'Äá»‘i tÆ°á»£ng', 'NgÆ°á»i gá»­i', 'Má»©c Ä‘á»™'],
    rows: [
      {
        id: 'report-01',
        cells: ['RP-260618-009', 'NgÆ°á»i chÆ¡i', 'LÃª HoÃ ng CÆ°á»ng', 'Thanh Minh', 'Æ¯u tiÃªn cao'],
        status: 'Äang xá»­ lÃ½',
        statusTone: 'warning',
        filters: ['NgÆ°á»i chÆ¡i', 'Æ¯u tiÃªn cao'],
        actions: ['Má»Ÿ há»“ sÆ¡', 'KhÃ³a táº¡m'],
      },
      {
        id: 'report-02',
        cells: ['RP-260618-014', 'BÃ i viáº¿t', 'BÃ i viáº¿t #POST-2248', 'Ngá»c Anh', 'Trung bÃ¬nh'],
        status: 'Chá» duyá»‡t',
        statusTone: 'warning',
        filters: ['BÃ i viáº¿t'],
        actions: ['áº¨n bÃ i', 'Bá» qua'],
      },
      {
        id: 'report-03',
        cells: ['RP-260617-033', 'SÃ¢n', 'SÃ¢n Tháº£o Äiá»n', 'Quá»‘c Huy', 'Æ¯u tiÃªn cao'],
        status: 'QuÃ¡ háº¡n',
        statusTone: 'danger',
        filters: ['SÃ¢n', 'Æ¯u tiÃªn cao'],
        actions: ['LiÃªn há»‡ chá»§ sÃ¢n', 'HoÃ n tiá»n'],
      },
      {
        id: 'report-04',
        cells: ['RP-260617-040', 'CLB', 'Há»“ TÃ¢y Smashers', 'Minh Äá»©c', 'Tháº¥p'],
        status: 'ÄÃ£ pháº£n há»“i',
        statusTone: 'success',
        filters: ['CLB'],
        actions: ['Xem káº¿t quáº£'],
      },
    ],
    queueTitle: 'Æ¯u tiÃªn kiá»ƒm duyá»‡t',
    queues: [
      { label: 'Æ¯u tiÃªn cao', value: '8', tone: 'danger' },
      { label: 'Chá» pháº£n há»“i ngÆ°á»i gá»­i', value: '14', tone: 'info' },
      { label: 'Cáº§n khÃ³a táº¡m', value: '4', tone: 'warning' },
    ],
  },
  posts: {
    id: 'posts',
    eyebrow: 'Cá»™ng Ä‘á»“ng',
    title: 'Kiá»ƒm duyá»‡t bÃ i viáº¿t cá»™ng Ä‘á»“ng',
    description: 'Duyá»‡t bÃ i Ä‘Äƒng má»›i, xá»­ lÃ½ ná»™i dung bá»‹ bÃ¡o cÃ¡o, quáº£n lÃ½ tráº¡ng thÃ¡i hiá»ƒn thá»‹ vÃ  nhÃ£n ná»™i dung cá»™ng Ä‘á»“ng.',
    primaryAction: 'áº¨n bÃ i hÃ ng loáº¡t',
    searchPlaceholder: 'TÃ¬m tiÃªu Ä‘á», tÃ¡c giáº£, hashtag...',
    filters: ['Táº¥t cáº£', 'Chá» duyá»‡t', 'Äang hiá»ƒn thá»‹', 'Bá»‹ bÃ¡o cÃ¡o', 'ÄÃ£ áº©n'],
    stats: [
      { label: 'BÃ i má»›i hÃ´m nay', value: '186', helper: '72 bÃ i cÃ³ áº£nh/video', icon: FileText },
      { label: 'Chá» duyá»‡t', value: '24', helper: 'Tá»± Æ°u tiÃªn bÃ i bá»‹ bÃ¡o cÃ¡o', icon: ClipboardCheck },
      { label: 'Bá»‹ bÃ¡o cÃ¡o', value: '17', helper: '5 bÃ i cÃ³ nhiá»u bÃ¡o cÃ¡o', icon: Flag },
      { label: 'ÄÃ£ áº©n', value: '9', helper: 'Trong 24 giá» gáº§n nháº¥t', icon: XCircle },
    ],
    columns: ['BÃ i viáº¿t', 'TÃ¡c giáº£', 'Chá»§ Ä‘á»', 'TÆ°Æ¡ng tÃ¡c', 'BÃ¡o cÃ¡o'],
    rows: [
      {
        id: 'post-01',
        cells: ['Kinh nghiá»‡m chá»n vá»£t cho ngÆ°á»i má»›i', 'Minh Khang', 'Ká»¹ thuáº­t', '428 lÆ°á»£t', '0'],
        status: 'Äang hiá»ƒn thá»‹',
        statusTone: 'success',
        filters: ['Äang hiá»ƒn thá»‹'],
        actions: ['Xem', 'Ghim'],
      },
      {
        id: 'post-02',
        cells: ['TÃ¬m ngÆ°á»i giao lÆ°u tá»‘i nay á»Ÿ Quáº­n 7', 'Lan Anh', 'TÃ¬m tráº­n', '96 lÆ°á»£t', '1'],
        status: 'Chá» duyá»‡t',
        statusTone: 'warning',
        filters: ['Chá» duyá»‡t'],
        actions: ['Duyá»‡t', 'Sá»­a nhÃ£n'],
      },
      {
        id: 'post-03',
        cells: ['Review sÃ¢n má»›i táº¡i Thá»§ Äá»©c', 'HoÃ ng Nam', 'ÄÃ¡nh giÃ¡ sÃ¢n', '312 lÆ°á»£t', '6'],
        status: 'Bá»‹ bÃ¡o cÃ¡o',
        statusTone: 'danger',
        filters: ['Bá»‹ bÃ¡o cÃ¡o'],
        actions: ['áº¨n bÃ i', 'Nháº¯c nhá»Ÿ'],
      },
      {
        id: 'post-04',
        cells: ['Lá»‹ch táº­p footwork tuáº§n nÃ y', 'Pickle Coach', 'Táº­p luyá»‡n', '154 lÆ°á»£t', '0'],
        status: 'Äang hiá»ƒn thá»‹',
        statusTone: 'success',
        filters: ['Äang hiá»ƒn thá»‹'],
        actions: ['Xem', 'ÄÆ°a vÃ o ná»•i báº­t'],
      },
    ],
    queueTitle: 'BÃ i cáº§n kiá»ƒm tra',
    queues: [
      { label: 'Chá» duyá»‡t', value: '24', tone: 'warning' },
      { label: 'Bá»‹ bÃ¡o cÃ¡o nhiá»u láº§n', value: '5', tone: 'danger' },
      { label: 'Cáº§n gáº¯n nhÃ£n', value: '13', tone: 'info' },
    ],
  },
  reviews: {
    id: 'reviews',
    eyebrow: 'ÄÃ¡nh giÃ¡',
    title: 'Kiá»ƒm duyá»‡t Ä‘Ã¡nh giÃ¡',
    description: 'Xem Ä‘Ã¡nh giÃ¡ sÃ¢n vÃ  ngÆ°á»i chÆ¡i, xá»­ lÃ½ Ä‘Ã¡nh giÃ¡ bá»‹ bÃ¡o cÃ¡o, ná»™i dung khÃ´ng phÃ¹ há»£p hoáº·c nghi ngá» spam.',
    primaryAction: 'Xuáº¥t Ä‘Ã¡nh giÃ¡',
    searchPlaceholder: 'TÃ¬m ngÆ°á»i Ä‘Ã¡nh giÃ¡, sÃ¢n, ná»™i dung...',
    filters: ['Táº¥t cáº£', 'Chá» duyá»‡t', 'ÄÃ£ hiá»ƒn thá»‹', 'Bá»‹ bÃ¡o cÃ¡o', 'Spam'],
    stats: [
      { label: 'ÄÃ¡nh giÃ¡ má»›i', value: '92', helper: 'Äiá»ƒm trung bÃ¬nh 4,6/5', icon: Star },
      { label: 'Chá» duyá»‡t', value: '15', helper: 'CÃ³ tá»« khÃ³a nháº¡y cáº£m', icon: ClipboardCheck },
      { label: 'Bá»‹ bÃ¡o cÃ¡o', value: '11', helper: 'Chá»§ sÃ¢n/ngÆ°á»i chÆ¡i khiáº¿u náº¡i', icon: Flag },
      { label: 'áº¨n trong tuáº§n', value: '7', helper: 'Do spam hoáº·c cÃ´ng kÃ­ch', icon: XCircle },
    ],
    columns: ['Äá»‘i tÆ°á»£ng', 'NgÆ°á»i Ä‘Ã¡nh giÃ¡', 'Äiá»ƒm', 'Ná»™i dung', 'BÃ¡o cÃ¡o'],
    rows: [
      {
        id: 'review-01',
        cells: ['Diamond Q7', 'Nguyá»…n VÄƒn An', '5 sao', 'SÃ¢n sáº¡ch, Ã¡nh sÃ¡ng tá»‘t', '0'],
        status: 'ÄÃ£ hiá»ƒn thá»‹',
        statusTone: 'success',
        filters: ['ÄÃ£ hiá»ƒn thá»‹'],
        actions: ['Xem', 'ÄÃ¡nh dáº¥u ná»•i báº­t'],
      },
      {
        id: 'review-02',
        cells: ['LÃª HoÃ ng CÆ°á»ng', 'Thanh Minh', '2 sao', 'ThÆ°á»ng xuyÃªn bá» tráº­n', '2'],
        status: 'Bá»‹ bÃ¡o cÃ¡o',
        statusTone: 'danger',
        filters: ['Bá»‹ bÃ¡o cÃ¡o'],
        actions: ['áº¨n', 'YÃªu cáº§u báº±ng chá»©ng'],
      },
      {
        id: 'review-03',
        cells: ['Há»“ TÃ¢y Club', 'HoÃ i Nam', '4 sao', 'GiÃ¡ hÆ¡i cao cuá»‘i tuáº§n', '0'],
        status: 'Chá» duyá»‡t',
        statusTone: 'warning',
        filters: ['Chá» duyá»‡t'],
        actions: ['Duyá»‡t', 'Sá»­a lá»—i chÃ­nh táº£'],
      },
      {
        id: 'review-04',
        cells: ['Tháº£o Äiá»n Court', 'TÃ i khoáº£n má»›i', '1 sao', 'Ná»™i dung láº·p láº¡i nhiá»u láº§n', '4'],
        status: 'Spam',
        statusTone: 'danger',
        filters: ['Spam'],
        actions: ['XÃ³a', 'KhÃ³a tÃ i khoáº£n'],
      },
    ],
    queueTitle: 'Cáº£nh bÃ¡o Ä‘Ã¡nh giÃ¡',
    queues: [
      { label: 'Nghi ngá» spam', value: '6', tone: 'danger' },
      { label: 'Cáº§n báº±ng chá»©ng', value: '9', tone: 'warning' },
      { label: 'Chá» pháº£n há»“i', value: '11', tone: 'info' },
    ],
  },
  transactions: {
    id: 'transactions',
    eyebrow: 'TÃ i chÃ­nh',
    title: 'Giao dá»‹ch, hoÃ n tiá»n, Ä‘á»‘i soÃ¡t',
    description: 'Theo dÃµi thanh toÃ¡n booking, lá»‡ phÃ­ giáº£i Ä‘áº¥u, yÃªu cáº§u hoÃ n tiá»n, phÃ­ ná»n táº£ng vÃ  Ä‘á»‘i soÃ¡t vá»›i chá»§ sÃ¢n.',
    primaryAction: 'Äá»‘i soÃ¡t hÃ´m nay',
    searchPlaceholder: 'TÃ¬m mÃ£ giao dá»‹ch, ngÆ°á»i tráº£, booking...',
    filters: ['Táº¥t cáº£', 'ThÃ nh cÃ´ng', 'Chá» Ä‘á»‘i soÃ¡t', 'HoÃ n tiá»n', 'Tháº¥t báº¡i'],
    stats: [
      { label: 'Doanh thu hÃ´m nay', value: '486,2tr', helper: '1.182 giao dá»‹ch thÃ nh cÃ´ng', icon: Banknote },
      { label: 'Chá» Ä‘á»‘i soÃ¡t', value: '94', helper: 'Tá»•ng 128,6tr', icon: ClipboardCheck },
      { label: 'YÃªu cáº§u hoÃ n tiá»n', value: '18', helper: '6 yÃªu cáº§u quÃ¡ 24 giá»', icon: RefreshCcw },
      { label: 'Tháº¥t báº¡i', value: '27', helper: 'Äa sá»‘ do háº¿t háº¡n OTP', icon: XCircle },
    ],
    columns: ['MÃ£ giao dá»‹ch', 'Nguá»“n tiá»n', 'LiÃªn káº¿t', 'Sá»‘ tiá»n', 'Cá»•ng thanh toÃ¡n'],
    rows: [
      {
        id: 'transaction-01',
        cells: ['TXN-260618-8841', 'Nguyá»…n VÄƒn An', 'BK-260618-0142', '520.000Ä‘', 'VNPay'],
        status: 'ThÃ nh cÃ´ng',
        statusTone: 'success',
        filters: ['ThÃ nh cÃ´ng'],
        actions: ['BiÃªn nháº­n', 'Äá»‘i soÃ¡t'],
      },
      {
        id: 'transaction-02',
        cells: ['TXN-260618-8898', 'Tráº§n Má»¹ Linh', 'BK-260618-0157', '680.000Ä‘', 'Momo'],
        status: 'Chá» Ä‘á»‘i soÃ¡t',
        statusTone: 'warning',
        filters: ['Chá» Ä‘á»‘i soÃ¡t'],
        actions: ['XÃ¡c nháº­n', 'Gáº¯n ghi chÃº'],
      },
      {
        id: 'transaction-03',
        cells: ['TXN-260617-7712', 'Pháº¡m Quá»‘c Huy', 'BK-260617-0288', '420.000Ä‘', 'Tháº» ná»™i Ä‘á»‹a'],
        status: 'HoÃ n tiá»n',
        statusTone: 'info',
        filters: ['HoÃ n tiá»n'],
        actions: ['Duyá»‡t hoÃ n', 'Tá»« chá»‘i'],
      },
      {
        id: 'transaction-04',
        cells: ['TXN-260617-7621', 'Äá»— Háº£i Nam', 'TOUR-2607-002', '350.000Ä‘', 'VNPay'],
        status: 'Tháº¥t báº¡i',
        statusTone: 'danger',
        filters: ['Tháº¥t báº¡i'],
        actions: ['Xem lá»—i', 'Gá»­i láº¡i link'],
      },
    ],
    queueTitle: 'TÃ i chÃ­nh cáº§n duyá»‡t',
    queues: [
      { label: 'Chá» Ä‘á»‘i soÃ¡t', value: '94', tone: 'warning' },
      { label: 'HoÃ n tiá»n quÃ¡ háº¡n', value: '6', tone: 'danger' },
      { label: 'Sai lá»‡ch phÃ­ ná»n táº£ng', value: '3', tone: 'info' },
    ],
  },
};

export const settingsGroups: SettingGroup[] = [
  {
    title: 'Äáº·t sÃ¢n vÃ  thanh toÃ¡n',
    description: 'Thiáº¿t láº­p thá»i gian giá»¯ chá»—, phÃ­ ná»n táº£ng vÃ  chÃ­nh sÃ¡ch hoÃ n tiá»n tá»± Ä‘á»™ng.',
    items: [
      {
        label: 'Thá»i gian giá»¯ chá»— chÆ°a thanh toÃ¡n',
        helper: 'Ãp dá»¥ng cho booking online trÆ°á»›c khi tá»± há»§y.',
        value: '5 phÃºt',
        enabled: true,
      },
      {
        label: 'Cho phÃ©p hoÃ n tiá»n tá»± Ä‘á»™ng',
        helper: 'Admin váº«n cÃ³ thá»ƒ duyá»‡t thá»§ cÃ´ng cÃ¡c trÆ°á»ng há»£p Ä‘áº·c biá»‡t.',
        value: 'Báº­t',
        enabled: true,
      },
      {
        label: 'PhÃ­ ná»n táº£ng máº·c Ä‘á»‹nh',
        helper: 'TÃ­nh trÃªn tá»•ng giÃ¡ trá»‹ booking thÃ nh cÃ´ng.',
        value: '5%',
      },
    ],
  },
  {
    title: 'Kiá»ƒm duyá»‡t cá»™ng Ä‘á»“ng',
    description: 'Cáº¥u hÃ¬nh hÃ ng chá» bÃ i viáº¿t, Ä‘Ã¡nh giÃ¡, bÃ¡o cÃ¡o vÃ  má»©c Ä‘á»™ nháº¡y cáº£m cá»§a bá»™ lá»c ná»™i dung.',
    items: [
      {
        label: 'Duyá»‡t bÃ i viáº¿t cÃ³ nhiá»u bÃ¡o cÃ¡o',
        helper: 'Tá»± Ä‘Æ°a bÃ i viáº¿t vÃ o hÃ ng chá» khi cÃ³ tá»« 3 bÃ¡o cÃ¡o trá»Ÿ lÃªn.',
        value: 'Báº­t',
        enabled: true,
      },
      {
        label: 'áº¨n táº¡m Ä‘Ã¡nh giÃ¡ nghi ngá» spam',
        helper: 'Giáº£m hiá»ƒn thá»‹ Ä‘Ã¡nh giÃ¡ láº·p ná»™i dung hoáº·c tá»« tÃ i khoáº£n má»›i.',
        value: 'Báº­t',
        enabled: true,
      },
      {
        label: 'SLA xá»­ lÃ½ bÃ¡o cÃ¡o Æ°u tiÃªn cao',
        helper: 'DÃ¹ng Ä‘á»ƒ cáº£nh bÃ¡o trong dashboard admin.',
        value: '30 phÃºt',
      },
    ],
  },
  {
    title: 'Báº£o máº­t vÃ  phÃ¢n quyá»n',
    description: 'Quáº£n lÃ½ Ä‘Äƒng nháº­p admin, nháº­t kÃ½ thao tÃ¡c vÃ  cáº£nh bÃ¡o truy cáº­p báº¥t thÆ°á»ng.',
    items: [
      {
        label: 'Báº¯t buá»™c OTP khi Ä‘Äƒng nháº­p admin',
        helper: 'Ãp dá»¥ng cho toÃ n bá»™ tÃ i khoáº£n cÃ³ quyá»n quáº£n trá»‹.',
        value: 'Báº­t',
        enabled: true,
      },
      {
        label: 'LÆ°u nháº­t kÃ½ thao tÃ¡c nháº¡y cáº£m',
        helper: 'Bao gá»“m khÃ³a tÃ i khoáº£n, duyá»‡t hoÃ n tiá»n, xÃ³a bÃ i viáº¿t.',
        value: '180 ngÃ y',
      },
      {
        label: 'Cáº£nh bÃ¡o Ä‘Äƒng nháº­p khÃ¡c tá»‰nh',
        helper: 'Gá»­i thÃ´ng bÃ¡o cho trÆ°á»Ÿng nhÃ³m váº­n hÃ nh.',
        value: 'Báº­t',
        enabled: true,
      },
    ],
  },
];
